# Generated by Django 4.1.5 on 2023-02-17 16:47

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='desc',
            field=tinymce.models.HTMLField(),
        ),
    ]
