# Generated by Django 4.1.5 on 2023-02-18 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_alter_course_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='image1',
            field=models.ImageField(default='static\\image\\email.png', upload_to='image'),
        ),
    ]
