# Generated by Django 4.1.5 on 2023-02-18 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_alter_course_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='image',
        ),
    ]
